### ISSUE TITLE
Отсутствуют метрики по некоторым нардепам

### ISSUE THREAD

**Issue by ytyukhnin** [uaoleg/vvkp.in.ua#10]
Добрый день,

Отличный сервис, просто и понятно :), вот только по некоторым нардепам отсутствуют метрики, что отфильтровывает их при поиске, не очень удобно при анализе.

http://zrada.today/#/search/praciuye,novator,konstruktyv

![screenshot_2015-09-11_15-30](https://cloud.githubusercontent.com/assets/3029254/9815959/39560de8-589a-11e5-9e9b-2256177109ea.png)

**Comment by uaoleg** [comment]
Это не баг, а фича =)

Алексеев отсутствовал на голосовании популистского закона о валютных кредитах. Поэтому ему не присвоен ни "плохой" ни "хороший" тег.

**Comment by ytyukhnin** [comment]
Теперь понятно. :) Тогда может добавить ещё фильтр "неважливо чи конструктив", "неважливо чи шокін-геть" и т.п.?

**Comment by uaoleg** [comment]
Может что-то такое и запилим, главное не переусложнить )
