### ISSUE TITLE
Новая  категория - пидарас/гей

### ISSUE THREAD

**Issue by Vanuan** [uaoleg/vvkp.in.ua#13]
http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=4295

**Comment by uaoleg** [comment]
Давайте лучше в евроинтеграторы это положим )

**Comment by Vanuan** [comment]
Эх, а как же ввкп... :)

**Comment by Vanuan** [comment]
Такой шанс упустили :)
